### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by ketchupstain** [apiaryio/s3-streaming-upload#19]
Version: 0.1.14

I followed the example provided but I intentionally entered incorrect s3 credentials to test the error handling.  The upload 'failed' callback is invoked every 5 seconds over and over.
upload.on('failed', function (err) {
    console.log('upload failed with error', err);
});

Then eventually node produces the following error and the 'failed' callback continues.

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Uploader.EventEmitter.addListener (events.js:160:15)
    at Uploader.EventEmitter.once (events.js:185:8)
    at Uploader.uploadChunks (D:\test\node_modules\s3-streaming-upload\lib\uploader.js:139:12)
    at null.<anonymous> (D:\test\node_modules\s3-streaming-upload\lib\uploader.js:54:20)
    at wrapper [as _onTimeout](timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

One way I can stop it is to call upload.finishUploads();
Am I missing something?

**Comment by abtris** [comment]
I released new version 0.2.0 this is based on new AWS SDK 2.x. Please, test if problem still exists.

**Comment by wonderdogone** [comment]
is anyone able to still recreate this?

**Comment by Almad** [comment]
(if not, I think this should be closed and someone can eventually reopen)
