### ISSUE TITLE
Creating an Uploader w/o a stream fails

### ISSUE THREAD

**Issue by mojodna** [apiaryio/s3-streaming-upload#29]
I was expecting to be able to create an `Uploader` and subsequently `.pipe()` my source stream to it, i.e.:

``` javascript
fs.createReadStream("/tmp/foo").pipe(new Uploader({
  bucket: myBucket,
  objectName: "foo"
});
```

This is the relevant stack trace:

```
/Users/seth/src/stamen/vapor-clock/node_modules/s3-streaming-upload/node_modules/readable-stream/lib/_stream_readable.js:822
  stream.on('end', function() {
         ^
TypeError: Cannot call method 'on' of undefined
    at Readable.wrap (/Users/seth/src/stamen/vapor-clock/node_modules/s3-streaming-upload/node_modules/readable-stream/lib/_stream_readable.js:822:10)
    at Uploader.handleStream (/Users/seth/src/stamen/vapor-clock/node_modules/s3-streaming-upload/lib/uploader.js:86:14)
    at new Uploader (/Users/seth/src/stamen/vapor-clock/node_modules/s3-streaming-upload/lib/uploader.js:54:10)
```

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by abtris** [comment]
You can try use https://github.com/nathanpeck/s3-upload-stream this library supports pipe.

**Comment by Almad** [comment]
@abtris I think s3-streaming-upload should support it as well—or we should deprecate this library in the favour of s3-upload-stream.
